// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmmNWTU2lLlYf4G7V41AUoIza4dqh_DY4',
    appId: '1:5694579953:web:aeaee80edc733f31873550',
    messagingSenderId: '5694579953',
    projectId: 'seres-fd5ea',
    authDomain: 'seres-fd5ea.firebaseapp.com',
    storageBucket: 'seres-fd5ea.firebasestorage.app',
    measurementId: 'G-TL7KVH93VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6WIaVc-x7igh5gVGVeIrIf9c1-YLrso8',
    appId: '1:5694579953:android:0c43def3223dd862873550',
    messagingSenderId: '5694579953',
    projectId: 'seres-fd5ea',
    storageBucket: 'seres-fd5ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgeBDREdKt8df6aYnek0YfrBRmBexn1o0',
    appId: '1:5694579953:ios:5e4ef6de3440eb8b873550',
    messagingSenderId: '5694579953',
    projectId: 'seres-fd5ea',
    storageBucket: 'seres-fd5ea.firebasestorage.app',
    iosBundleId: 'com.example.SERES',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgeBDREdKt8df6aYnek0YfrBRmBexn1o0',
    appId: '1:5694579953:ios:5e4ef6de3440eb8b873550',
    messagingSenderId: '5694579953',
    projectId: 'seres-fd5ea',
    storageBucket: 'seres-fd5ea.firebasestorage.app',
    iosBundleId: 'com.example.SERES',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmmNWTU2lLlYf4G7V41AUoIza4dqh_DY4',
    appId: '1:5694579953:web:a50e6eadc2ffd2fd873550',
    messagingSenderId: '5694579953',
    projectId: 'seres-fd5ea',
    authDomain: 'seres-fd5ea.firebaseapp.com',
    storageBucket: 'seres-fd5ea.firebasestorage.app',
    measurementId: 'G-TRLEJRJ3ZE',
  );
}
